/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HDBViewer;

import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JScrollPane;
import org.tango.jhdb.data.HdbData;

/**
 *
 * @author pons
 */
public class ErrorDialog extends javax.swing.JFrame {
  
  MultiLineTable table;
  JScrollPane tableView;
  String[] colNMames = {"Time","Errors"};

  /**
   * Creates new form ErrorDialog
   */
  public ErrorDialog() {
    
    initComponents();
    
    table = new MultiLineTable();
    tableView = new JScrollPane(table);
    tableView.setPreferredSize(new Dimension(640,480));
    tablePanel.add(tableView, BorderLayout.CENTER);
    
    setTitle("HDB Errors");
    
  }
  
  public void reset() {
    table.reset();    
  }
  
  public void commit() {
    table.setColumnName(colNMames);
    table.dataChanged();
  }
  
  public void addError(String name,HdbData err) {    
    table.add(name+"\n"+err.getErrorMessage(), 1, err.getDataTime(), 1);
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    tablePanel = new javax.swing.JPanel();
    btnPanel = new javax.swing.JPanel();
    dismissButton = new javax.swing.JButton();

    tablePanel.setLayout(new java.awt.BorderLayout());
    getContentPane().add(tablePanel, java.awt.BorderLayout.CENTER);

    btnPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

    dismissButton.setText("Dismiss");
    dismissButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        dismissButtonActionPerformed(evt);
      }
    });
    btnPanel.add(dismissButton);

    getContentPane().add(btnPanel, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void dismissButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dismissButtonActionPerformed
    // TODO add your handling code here:
    setVisible(false);
  }//GEN-LAST:event_dismissButtonActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel btnPanel;
  private javax.swing.JButton dismissButton;
  private javax.swing.JPanel tablePanel;
  // End of variables declaration//GEN-END:variables
}
