/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HDBViewer;

import fr.esrf.tangoatk.widget.util.ATKGraphicsUtils;
import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author pons
 */
public class IDSelectionDlg extends javax.swing.JDialog {

  private static IDSelectionDlg dialog = null;
  private static ArrayList<Integer> retIDs = null;
  
  /**
   * Creates new form IDSelectionDlg
   */
  public IDSelectionDlg() {
    super((JFrame)null,true);
    initComponents();
    setTitle("Select Array item(s)");
  }
  
  public static ArrayList<Integer> getIds(int maxLength) {
    
    retIDs = null;
    
    if(dialog==null)
      dialog = new IDSelectionDlg();
    
    if(maxLength>0)
      dialog.setInfoText("Array length: " + maxLength);
    else
      dialog.setInfoText("");

    ATKGraphicsUtils.centerDialog(dialog, 400, 200);
    dialog.setVisible(true);
    return retIDs;
    
  }
  
  private void setInfoText(String msg) {
    infoLabel.setText(msg);
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    jScrollPane2 = new javax.swing.JScrollPane();
    infoTextArea = new javax.swing.JTextArea();
    jScrollPane1 = new javax.swing.JScrollPane();
    idText = new javax.swing.JTextArea();
    btnPanel = new javax.swing.JPanel();
    infoLabel = new javax.swing.JLabel();
    clearButton = new javax.swing.JButton();
    selectButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();

    infoTextArea.setEditable(false);
    infoTextArea.setColumns(20);
    infoTextArea.setRows(5);
    infoTextArea.setText("Enter list of ids to select. \nThe list of ids can be specified either as a comma\nseparated list of numbers or ranges (with each\nnumber in the range 0 to N-1 inclusive).\nEx: 0,1,2,44-67,82-99");
    jScrollPane2.setViewportView(infoTextArea);

    getContentPane().add(jScrollPane2, java.awt.BorderLayout.NORTH);

    idText.setColumns(20);
    idText.setRows(3);
    jScrollPane1.setViewportView(idText);

    getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

    btnPanel.setLayout(new java.awt.GridBagLayout());

    infoLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
    btnPanel.add(infoLabel, gridBagConstraints);

    clearButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    clearButton.setText("Clear");
    clearButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        clearButtonActionPerformed(evt);
      }
    });
    btnPanel.add(clearButton, new java.awt.GridBagConstraints());

    selectButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    selectButton.setText("Select");
    selectButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        selectButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
    btnPanel.add(selectButton, gridBagConstraints);

    cancelButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    cancelButton.setText("Cancel");
    cancelButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
    btnPanel.add(cancelButton, gridBagConstraints);

    getContentPane().add(btnPanel, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    setVisible(false);
  }//GEN-LAST:event_cancelButtonActionPerformed

  private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed

    retIDs = new ArrayList<Integer>();
    String[] idDef = idText.getText().split(",");
    
    try {
      
      for(int i=0;i<idDef.length;i++) {
        int mIdx = idDef[i].indexOf('-');
        if(mIdx!=-1) {
          
          // Range x-y
          String sR = idDef[i].substring(0,mIdx);
          String eR = idDef[i].substring(mIdx+1,idDef[i].length());
          int s = Integer.parseInt(sR);
          int e = Integer.parseInt(eR);
          if( s>e )
            throw new Exception("Invalid range definition " + idDef[i]);
          
          for(int j=s;j<=e;j++) {
            if(retIDs.contains(j))
              throw new Exception("Invalid id list. Overlap detected");
            retIDs.add(j);
          }
          
        } else {
          
          // Simple value
          int j = Integer.parseInt(idDef[i]);
          if(retIDs.contains(j))
              throw new Exception("Invalid id list. Overlap detected");
            retIDs.add(j);
          
        }
      
      }

      setVisible(false);
    
    } catch (NumberFormatException e) {
      Utils.showError("Invalid number " + e.getMessage());
    } catch (Exception e) {
      Utils.showError(e.getMessage());
    }

  }//GEN-LAST:event_selectButtonActionPerformed

  private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
    retIDs = new ArrayList<Integer>();
    setVisible(false);
  }//GEN-LAST:event_clearButtonActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel btnPanel;
  private javax.swing.JButton cancelButton;
  private javax.swing.JButton clearButton;
  private javax.swing.JTextArea idText;
  private javax.swing.JLabel infoLabel;
  private javax.swing.JTextArea infoTextArea;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JButton selectButton;
  // End of variables declaration//GEN-END:variables
}
