/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HDBViewer;

import fr.esrf.tangoatk.widget.attribute.NumberSpectrumTrend3DViewer;
import fr.esrf.tangoatk.widget.util.chart.JLAxis;
import java.awt.Dimension;

/**
 *
 * @author pons
 */
public class ImagePanel extends javax.swing.JPanel {

  MainPanel parent;
  
  // HDB Image
  NumberSpectrumTrend3DViewer image;
  boolean updateImageSelection=false;

  /**
   * Creates new form ImagePanel
   */
  public ImagePanel(MainPanel parent) {

    this.parent = parent;
    initComponents();
    
    image = new NumberSpectrumTrend3DViewer();
    imagePanel.add(image);
    setPreferredSize(new Dimension(800, 600));
    
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    imagePanel = new javax.swing.JPanel();
    imageBtnPanel = new javax.swing.JPanel();
    nameLabel = new javax.swing.JLabel();
    imageErrorCheck = new javax.swing.JCheckBox();

    setLayout(new java.awt.BorderLayout());

    imagePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    imagePanel.setLayout(new java.awt.BorderLayout());
    add(imagePanel, java.awt.BorderLayout.CENTER);

    imageBtnPanel.setLayout(new java.awt.GridBagLayout());
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
    imageBtnPanel.add(nameLabel, gridBagConstraints);

    imageErrorCheck.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    imageErrorCheck.setText("View Errors");
    imageErrorCheck.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        imageErrorCheckActionPerformed(evt);
      }
    });
    imageBtnPanel.add(imageErrorCheck, new java.awt.GridBagConstraints());

    add(imageBtnPanel, java.awt.BorderLayout.SOUTH);
  }// </editor-fold>//GEN-END:initComponents

  private void imageErrorCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageErrorCheckActionPerformed

    parent.buildImageData();

  }//GEN-LAST:event_imageErrorCheckActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel imageBtnPanel;
  javax.swing.JCheckBox imageErrorCheck;
  private javax.swing.JPanel imagePanel;
  javax.swing.JLabel nameLabel;
  // End of variables declaration//GEN-END:variables
}
