/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HDBViewer;

import javax.swing.ImageIcon;

/**
 *
 * @author pons
 */
public class ThreadPanel extends javax.swing.JPanel {

  /**
   * Creates new form ThreadPanel
   */
  public ThreadPanel() {
    initComponents();
  }
  
  void setMessage(String message) {
    messageLabel.setText(message);
  }
  
  void setProgress(double p,String prefix) {
    
    int pi = (int)(p*100.0 + 0.5);

    progressBar.setValue(pi);

    String prg;
    if(prefix!=null)
      prg = prefix + " - " + Integer.toString(pi) + "%";
    else
      prg = Integer.toString(pi) + "%";
    
    progressBar.setString(prg);
    
  }
  
  void hideProgress() {
    progressBar.setVisible(false);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    iconLabel = new javax.swing.JLabel();
    messageLabel = new javax.swing.JLabel();
    progressBar = new javax.swing.JProgressBar();

    setLayout(new java.awt.GridBagLayout());

    iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HDBViewer/wait_anim.gif"))); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
    add(iconLabel, gridBagConstraints);

    messageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    messageLabel.setText("Message");
    messageLabel.setPreferredSize(new java.awt.Dimension(200, 15));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    add(messageLabel, gridBagConstraints);

    progressBar.setStringPainted(true);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    add(progressBar, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel iconLabel;
  private javax.swing.JLabel messageLabel;
  private javax.swing.JProgressBar progressBar;
  // End of variables declaration//GEN-END:variables
}
